package za.co.tracemates;

import com.codename1.components.InteractionDialog;
import com.codename1.io.ConnectionRequest;
import com.codename1.io.JSONParser;
import com.codename1.io.Log;
import com.codename1.io.NetworkManager;
import com.codename1.location.Location;
import com.codename1.location.LocationManager;
import com.codename1.ui.Button;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.geom.Dimension;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Command;
import com.codename1.ui.Dialog;
import com.codename1.ui.FontImage;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.NavigationCommand;
import com.codename1.ui.RadioButton;
import com.codename1.ui.Slider;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BoxLayout;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class TraceMatesDriver {

    private Form current;
    private Resources theme;

    private Form home;
    ConnectionRequest request = null;
    Location  position = null;

    private String fmURL = "http://tracemates.foodmates.co.za/services/rest/v1/tracemates.php";
    private TextField trackingIdTextFld;
    private Boolean tracking = false;
    private String trackingId = "";
    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }




        //create and build the home Form
        home = new Form("TraceMates");
        home.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
        trackingIdTextFld = new TextField();
        trackingIdTextFld.setHint("Tracking ID");
        home.addComponent(trackingIdTextFld);
        Button start = new Button("Start Tracking");

        InteractionDialog dialog = new InteractionDialog("Start Tracking");
        dialog.setLayout(new BorderLayout());
        dialog.add(BorderLayout.CENTER, new Label("Starting tracking for parcel xyz"));
        Button ok = new Button("Ok");
        ok.addActionListener((ee) -> dialog.dispose());
        Button close = new Button("Cancel");
        close.addActionListener((ee) -> dialog.dispose());
        dialog.addComponent(BorderLayout.EAST, close);
        dialog.addComponent(BorderLayout.WEST, ok);
        Dimension pre = dialog.getContentPane().getPreferredSize();





        start.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {

                Dialog.show("Start Tracking", "Tracking parcel xyz", "Ok", "Cancel");
                //dialog.show(0, 0, Display.getInstance().getDisplayWidth() - (pre.getWidth() + pre.getWidth() / 6), 0);
                trackingId = trackingIdTextFld.getText();
                tracking = true;
                tracker();

            }
        });
        home.addComponent(start);
        Button stop = new Button("Stop Tracking");
        stop.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {

                Dialog.show("Stop Tracking", "Parcel xyz", "Ok", "Cancel");
                tracking = false;
                tracker();
            }
        });
        home.addComponent(stop);

        Button b1 = new Button("Show a Dialog");
        b1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                Dialog.show("Dialog Title", "Dialog Body", "Ok", "Cancel");
            }
        });
        //home.addComponent(b1);

        //Create Form1 and Form2 and set a Back Command to navigate back to the home Form
        Form form1 = new Form("Form1");
        setBackCommand(form1);
        Form form2 = new Form("Form2");
        setBackCommand(form2);

        //Add navigation commands to the home Form
        //NavigationCommand homeCommand = new NavigationCommand("Home");
        //homeCommand.setNextForm(home);
        //home.getToolbar().addCommandToSideMenu(homeCommand);

        //NavigationCommand cmd1 = new NavigationCommand("Form1");
        //cmd1.setNextForm(form1);
        //home.getToolbar().addCommandToSideMenu(cmd1);

//        NavigationCommand cmd2 = new NavigationCommand("Form2");
        //      cmd2.setNextForm(form2);
        //    home.getToolbar().addCommandToSideMenu(cmd2);


        home.show();
    }

    protected void setBackCommand(Form f) {
        Command back = new Command("") {

            @Override
            public void actionPerformed(ActionEvent evt) {
                home.showBack();
            }
        };
        Image img = FontImage.createMaterial(FontImage.MATERIAL_ARROW_BACK, UIManager.getInstance().getComponentStyle("TitleCommand"));
        back.setIcon(img);
        f.getToolbar().addCommandToLeftBar(back);
        f.getToolbar().setTitleCentered(true);
        f.setBackCommand(back);
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
    }

    public void destroy() {
    }

    private void tracker(){
        while (tracking) {
            try {
                request = new ConnectionRequest();
                position = LocationManager.getLocationManager().getCurrentLocation();
                String longtitude = Double.toString(position.getLongitude());
                String latitude = Double.toString(position.getLatitude());
                trackingId = trackingIdTextFld.getText();

                request.setUrl(fmURL);
                request.setPost(false);
                request.setHttpMethod("POST");
                request.setContentType("application/x-www-form-urlencoded");
                request.addRequestHeader("Connection", "Keep-Alive");
                request.addArgument("function", "add_tracker_location");
                request.addArgument("tracker_id", "tracker_id1");
                request.addArgument("longitude", longtitude);
                request.addArgument("latitude", latitude);

                Log.p(request.getUrl());

                NetworkManager.getInstance().addToQueueAndWait(request);
                JSONParser p = new JSONParser();
                Map<String, Object> result = p.parseJSON(new InputStreamReader(new ByteArrayInputStream(request.getResponseData())));
                Thread.sleep(15000);
                Log.p("tracking code= " + trackingId);
                Log.p("longitude= " + longtitude);
                Log.p("latitude= " + latitude);
                Log.p(result.toString());
            } catch (IOException e) {
                e.printStackTrace();
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    //private void startTracking(){}


}